# Generated by Django 5.2.3 on 2025-06-16 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='app',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='package',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='sub_category',
            field=models.CharField(max_length=100),
        ),
    ]
