# Generated by Django 5.2.3 on 2025-06-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_app_screenshot_app_uploaded_by_alter_app_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
